version: "3.7"
networks:
  net-dict:
    driver: bridge

services:
  postgres:
    image: postgres:11.6
    container_name: 'postgres-dict'
    restart: on-failure
    networks:
      net-dict:
        aliases:
          - db-dict
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql
    ports:
      - ${DB_PORT}:5432