version: "3.7"
networks:
  net-dict:
    driver: bridge

services:
  postgres-dict:
    image: postgres:11.6
    container_name: 'postgres-dict'
    restart: on-failure
    networks:
      net-dict:
        aliases:
          - db-dict
    command: -p ${DB_PORT}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/

  dictionary:
    build: .
    container_name: 'dictionary'
    restart: on-failure
    networks:
      net-dict:
        aliases:
          - dict
    depends_on:
      - postgres-dict
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      - DEBUG=${DEBUG}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - API_PORT=${API_PORT}
      - API_HOST=${API_HOST}
